# Generated by Django 4.1.7 on 2023-03-23 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказанная книга', 'verbose_name_plural': 'Заказанные книги'},
        ),
    ]
